In [2]:
import minicamels as mc
import pandas as pd

ds = mc.MiniCamels("C:\\Users\\roswe\\Desktop\\minicamels\\data")

basins = ds.basins()  # Array of all basin ID's - ID's ONLY NOT NAMES

attrs = ds.attributes()

basins

    basin_id                                         basin_name
0   01013500                   Fish River near Fort Kent, Maine
1   01580000                            DEER CREEK AT ROCKS, MD
2   02016000            COWPASTURE RIVER NEAR CLIFTON FORGE, VA
3   02064000                      FALLING RIVER NEAR NARUNA, VA
4   02221525                    MURDER CREEK BELOW EATONTON, GA
5   02297310                        HORSE CREEK NEAR ARCADIA FL
6   02298123                   PRAIRIE CREEK NEAR FORT OGDEN FL
7   02371500                       CONECUH RIVER AT BRANTLEY AL
8   02415000                HILLABEE CREEK NEAR HACKNEYVILLE AL
9   03504000           NANTAHALA RIVER NEAR RAINBOW SPRINGS, NC
10  04057510             STURGEON RIVER NEAR NAHMA JUNCTION, MI
11  04124000                    MANISTEE RIVER NEAR SHERMAN, MI
12  04196800                     Tymochtee Creek at Crawford OH
13  04213000                      Conneaut Creek at Conneaut OH
14  05488200                   English Creek near Knoxville, IA
15  06353000                         CEDAR CREEK NR RALEIGH, ND
16  06468170                      JAMES RIVER NR GRACE CITY, ND
17  07068000                      Current River at Doniphan, MO
18  07148400               Salt Fork Arkansas River nr Alva, OK
19  07167500                              OTTER C AT CLIMAX, KS
20  07346045               Black Cypress Bayou at Jefferson, TX
21  08164600                            Garcitas Ck nr Inez, TX
22  08194200                       San Casimiro Ck nr Freer, TX
23  10249300                     S TWIN R NR ROUND MOUNTAIN, NV
24  10258500                      PALM CYN C NR PALM SPRINGS CA
25  11143000                            BIG SUR R NR BIG SUR CA
26  11237500                          PITMAN C BL TAMARACK C CA
27  11274500                           ORESTIMBA C NR NEWMAN CA
28  11451100     NF CACHE C A HOUGH SPRING NR CLEARLAKE OAKS CA
29  11468500                            NOYO R NR FORT BRAGG CA
30  11523200            TRINITY R AB COFFEE C NR TRINITY CTR CA
31  12040500                   QUEETS RIVER NEAR CLEARWATER, WA
32  12048000                    DUNGENESS RIVER NEAR SEQUIM, WA
33  12092000                   PUYALLUP RIVER NEAR ELECTRON, WA
34  12095000           SOUTH PRAIRIE CREEK AT SOUTH PRAIRIE, WA
35  12147500           NORTH FORK TOLT RIVER NEAR CARNATION, WA
36  12175500                    THUNDER CREEK NEAR NEWHALEM, WA
37  12358500      Middle Fork Flathead River nr West Glacier MT
38  12374250                 Mill Cr ab Bassoo Cr nr Niarada MT
39  12390700                Prospect Creek at Thompson Falls MT
40  12447390                      ANDREWS CREEK NEAR MAZAMA, WA
41  13310700       SF SALMON RIVER NR KRASSEL RANGER STATION ID
42  13313000                    JOHNSON CREEK AT YELLOW PINE ID
43  13337000                          LOCHSA RIVER NR LOWELL ID
44  13338500                   SF CLEARWATER RIVER AT STITES ID
45  14092750  SHITIKE CR, AT PETERS PASTURE, NR WARM SPRINGS...
46  14308990       COW CREEK ABV GALESVILLE RES, NR AZALEA, OR.
47  14309500              WEST FORK COW CREEK NEAR GLENDALE, OR
48  14316700                     STEAMBOAT CREEK NEAR GLIDE, OR
49  14325000            SOUTH FORK COQUILLE RIVER AT POWERS, OR

In [3]:
attrs

,lat,lon,elev_mean,slope_mean,area_km2,mean_prcp,mean_pet,aridity,frac_snow,q_mean,runoff_ratio,hfd_mean,baseflow_index,soil_depth_pelletier,frac_forest,lai_max
basin_id,,,,,,,,,,,,,,,,
01013500,47.23739,-68.58264,250.31,21.64152,2252.70,3.126679,1.971555,0.630559,0.313440,1.699155,0.543437,207.250000,0.585226,7.404762,0.9063,4.167304
01580000,39.62997,-76.40331,174.30,12.44242,244.37,3.431728,2.527253,0.736437,0.081688,1.305300,0.380362,171.950000,0.715801,1.046154,0.4241,2.511604
02016000,37.79180,-79.75949,645.04,66.42056,1194.55,3.144815,2.573820,0.818433,0.102077,1.155713,0.367498,170.300000,0.497769,1.013858,0.9317,5.088656
02064000,37.12681,-78.95974,192.21,9.95686,427.77,3.095496,2.926439,0.945386,0.060601,0.929232,0.300188,168.450000,0.564004,1.070644,0.9090,4.344958
02221525,33.25236,-83.48128,176.01,7.55177,490.80,3.359124,3.142409,0.935485,0.009539,0.762009,0.226848,161.000000,0.529551,1.142454,0.8252,4.545543
02297310,27.19949,-81.98842,25.71,1.18116,528.38,3.841662,4.042907,1.052385,0.000000,0.926554,0.241186,268.000000,0.423763,49.638239,0.1446,1.797622
02298123,27.05200,-81.78453,21.75,0.82221,540.65,3.684448,3.525578,0.956881,0.000000,1.042803,0.283028,260.850000,0.503475,49.874488,0.1369,1.756440
02371500,31.57350,-86.25162,125.86,7.42604,1292.79,3.969984,3.147583,0.792845,0.004017,1.153419,0.290535,164.700000,0.523493,5.055682,0.6862,4.165486
02415000,33.06679,-85.87913,270.56,12.25237,491.38,4.055131,3.000596,0.739950,0.012469,1.474157,0.363529,162.850000,0.559165,1.101574,0.9106,4.606814
03504000,35.12750,-83.61861,1039.71,86.43459,134.52,5.603149,2.698901,0.481676,0.058991,3.682262,0.657177,165.600000,0.720317,0.989950,0.9516,4.545156
04057510,45.94302,-86.70570,228.86,4.66219,473.57,2.356333,2.035944,0.864031,0.253135,0.873568,0.370732,191.250000,0.650659,38.620770,0.9814,4.636695
04124000,44.43639,-85.69868,336.67,9.92703,2243.63,2.474482,2.604745,1.052643,0.226974,1.157520,0.467783,183.550000,0.886909,26.691025,0.7036,3.910929
04196800,40.92283,-83.34881,276.66,2.52382,608.07,2.674605,2.454083,0.917550,0.099312,0.909436,0.340026,166.250000,0.265576,48.047472,0.0048,1.814114
04213000,41.92700,-80.60397,322.72,10.20101,455.30,3.258936,2.309250,0.708590,0.162227,1.639385,0.503043,145.300000,0.373443,23.367156,0.9317,4.251683
05488200,41.30055,-93.04548,282.37,6.56634,234.21,2.663480,2.428881,0.911920,0.101821,0.728126,0.273374,217.650000,0.250112,31.185379,0.4427,2.072660
06353000,46.09167,-101.33374,767.71,9.54494,4526.51,1.135228,3.043100,2.680607,0.155792,0.042584,0.037512,201.150000,0.268676,1.824680,0.0001,1.244106
06468170,47.55805,-98.86289,516.41,4.68375,2809.10,1.307745,2.065572,1.579491,0.143379,0.076612,0.058583,217.300000,0.341760,46.112127,0.0030,1.864350
07068000,36.62200,-90.84762,293.50,12.06510,5318.59,3.404092,2.747050,0.806985,0.055511,1.333882,0.391847,180.600000,0.718142,2.158069,0.7417,4.914129
07148400,36.81503,-98.64814,545.41,9.72975,2544.50,1.909582,3.200512,1.676027,0.079878,0.118953,0.062293,203.900000,0.536771,12.858765,0.0005,0.963709
07167500,37.70821,-96.22360,383.36,10.91937,319.62,2.816464,2.721329,0.966222,0.052069,0.838547,0.297730,213.650000,0.212084,1.217659,0.0167,2.152201
07346045,32.77792,-94.35742,103.75,7.44495,959.89,3.582025,3.142319,0.877247,0.016890,0.900645,0.251435,159.300000,0.492232,1.653031,0.8518,3.815759
08164600,28.89138,-96.81915,37.19,1.85956,253.92,3.102590,3.777449,1.217515,0.000898,0.623875,0.201082,191.250000,0.116282,49.337875,0.0573,1.506488
08194200,27.96501,-98.96697,161.27,5.02405,1220.58,1.397216,3.619265,2.590341,0.000554,0.072299,0.051745,287.750000,0.042775,7.772397,0.0008,1.078335
10249300,38.88743,-117.24537,2256.43,98.85646,50.20,0.644565,3.356840,5.207913,0.312695,0.331079,0.513647,222.850000,0.630474,11.834951,0.0620,0.405882
10258500,33.74502,-116.53557,1329.18,116.14195,241.51,0.822899,3.141874,3.818054,0.004087,0.047011,0.057129,142.352941,0.298106,1.026316,0.2855,0.543803
11143000,36.24580,-121.77329,764.03,138.61035,120.61,2.836768,2.582941,0.910522,0.025438,2.022256,0.712873,144.600000,0.532805,0.664804,0.9458,3.256735
11237500,37.19856,-119.21373,2201.22,104.67149,59.82,2.928504,2.942183,1.004671,0.749857,1.878415,0.641425,220.000000,0.487675,0.980000,0.8069,1.576881
11274500,37.31549,-121.12521,377.44,54.47513,347.75,1.206446,2.749830,2.279281,0.000000,0.127311,0.105525,144.473684,0.230284,1.204489,0.3051,1.278519
11451100,39.16545,-122.61999,740.46,103.93357,155.09,2.961472,2.590332,0.874677,0.123536,1.814664,0.612758,135.350000,0.396907,0.906122,0.8707,2.214124
11468500,39.42822,-123.73779,276.08,45.14956,273.51,3.582883,2.717162,0.758373,0.000524,1.782064,0.497383,135.250000,0.389545,1.666667,1.0000,4.763059
11523200,41.11126,-122.70558,1614.41,139.34749,382.94,2.932423,2.561796,0.873611,0.431707,2.652417,0.904514,190.750000,0.587634,0.658497,0.9800,2.026643
12040500,47.53786,-124.31575,437.01,96.58146,1153.44,8.154612,1.899096,0.232886,0.067092,9.688438,1.188093,117.100000,0.515538,2.581522,0.9969,3.750003
12048000,48.01426,-123.13268,1263.46,183.83774,405.01,4.775127,2.517966,0.527309,0.498198,2.334860,0.488963,187.750000,0.679331,0.801926,0.9881,3.125671
12092000,46.90372,-122.03511,1330.94,172.20201,240.88,7.274496,2.076760,0.285485,0.513671,5.419860,0.745050,195.550000,0.694987,0.916877,0.9239,3.148019
12095000,47.13955,-122.09261,757.39,103.55868,205.84,4.560746,2.479700,0.543705,0.078232,2.658636,0.582939,144.950000,0.604888,3.172749,0.9717,4.377823
12147500,47.71232,-121.78873,601.12,112.82134,102.89,7.993348,1.957544,0.244897,0.159041,8.301802,1.038589,140.700000,0.627931,1.145833,1.0000,3.769461
12175500,48.67263,-121.07290,1538.75,245.56131,273.82,5.461752,2.188632,0.400720,0.690360,5.718302,1.046972,251.200000,0.671256,0.483801,0.7897,1.992663
12358500,48.49524,-114.01012,1559.24,106.51262,2939.19,3.330401,2.218183,0.666041,0.558849,2.338707,0.702230,237.450000,0.613435,0.700783,0.7376,2.467720
12374250,47.82966,-114.69763,1379.76,104.39721,50.79,2.243567,2.395138,1.067558,0.439806,0.394047,0.175634,219.250000,0.642851,1.171717,0.7973,2.878021
12390700,47.58605,-115.35515,1415.22,115.21011,470.23,3.035069,2.887216,0.951285,0.519487,1.131199,0.372709,216.250000,0.652728,0.729040,0.9955,3.310984
12447390,48.82292,-120.14592,1700.98,172.58264,58.10,2.559076,2.188394,0.855150,0.777311,1.365544,0.533608,241.300000,0.534020,0.472727,0.9643,1.199953
13310700,44.98694,-115.72500,1979.98,106.69118,853.13,3.047281,2.745451,0.900951,0.659424,1.404035,0.460750,231.250000,0.621746,0.715385,0.9654,1.891395
13313000,44.96167,-115.50000,2155.60,111.17973,561.94,3.630479,2.861130,0.788086,0.744536,1.413739,0.389408,236.850000,0.573368,1.146809,0.9807,1.712936
13337000,46.15083,-115.58722,1548.18,120.82851,3053.42,3.588318,2.329419,0.649168,0.564570,2.158771,0.601611,226.100000,0.615921,0.625456,0.9726,3.464977
13338500,46.08639,-115.97667,1418.36,110.26490,3027.00,2.325843,2.255713,0.969848,0.360817,0.726262,0.312258,219.650000,0.652414,0.870519,0.8078,3.271543
14092750,44.75039,-121.63340,1597.68,155.84779,57.48,4.591380,3.071489,0.668969,0.535953,3.271137,0.712452,190.450000,0.708062,1.061947,0.9807,2.933168
14308990,42.82318,-123.12589,987.04,96.62676,167.76,3.655584,3.064349,0.838265,0.135826,1.255903,0.343557,141.200000,0.551513,0.889680,1.0000,4.607646
14309500,42.80400,-123.61091,709.83,110.42527,224.92,4.977781,3.122204,0.627228,0.061255,2.457700,0.493734,125.550000,0.459455,0.894595,1.0000,4.227902
14316700,43.34984,-122.72894,952.26,119.08920,587.90,4.543400,2.277630,0.501305,0.176337,2.925937,0.643997,135.500000,0.508616,0.879292,1.0000,4.859652
14325000,42.89150,-124.07065,656.53,124.96889,443.07,6.297437,2.434652,0.386610,0.030203,4.072283,0.646657,125.900000,0.480769,0.990318,1.0000,4.150730

In [4]:
ds.load_all()

<xarray.Dataset> Size: 13MB
Dimensions:  (basin: 50, time: 10957)
Coordinates:
  * basin    (basin) StringDType(na_object=nan) 800B '01013500' ... '14325000'
  * time     (time) datetime64[ns] 88kB 1980-10-01 1980-10-02 ... 2010-09-30
Data variables:
    prcp     (basin, time) float32 2MB 3.1 4.24 8.02 15.27 ... 0.0 0.0 0.0 0.0
    tmax     (basin, time) float32 2MB 10.05 15.82 15.86 ... 21.31 22.73 24.84
    tmin     (basin, time) float32 2MB 2.11 5.24 7.81 3.66 ... 13.98 12.59 13.02
    srad     (basin, time) float32 2MB 192.6 206.3 165.4 ... 285.7 353.1 369.5
    vp       (basin, time) float32 2MB 711.3 898.6 ... 1.286e+03 1.289e+03
    qobs     (basin, time) float32 2MB 0.5528 0.5626 0.5604 ... 0.1877 0.1877
Attributes:
    Conventions:  CF-1.8
    basin_id:     01013500
    basin_name:   Fish River near Fort Kent, Maine
    area_km2:     2252.7
    lat:          47.23739
    lon:          -68.58264
    huc02:        01
    forcing:      Daymet
    created:      2026-03-30
    source:       CAMELS-US (Newman et al. 2015; Addor et al. 2017)